metadata

cookbook 'yum', git: 'git://github.com/opscode-cookbooks/yum.git'

cookbook 'ark',  git: 'git://github.com/opscode-cookbooks/ark.git'
cookbook 'java', git: 'git://github.com/opscode-cookbooks/java.git'

cookbook 'minitest-handler', git: 'git://github.com/btm/minitest-handler-cookbook.git'
